Upgrade to SDL 2.0
Globulation2/glob2 pull request #30
Opened 2020-09-03 05:06 UTC by Quipyowert2

Fixes #10.

2021-02-15 12:30 UTC, stephanemagnenat requested changes
Thank you very much for the upgrade! If you are available, please correct the small issue I pointed out. If you are not available, please tell us so that someone else can do it!

2021-02-15 12:30 UTC, stephanemagnenat commented on libgag/include/KeyPress.h
> +	KeyPress(SDL_Keysym& key, bool pressed);
Why not passing by value, afaik `SDL_keysym` is small, no? If passed by reference, I would use a const reference.

2021-02-15 12:30 UTC, stephanemagnenat commented on libgag/include/SDLGraphicContext.h
> +		static const bool verbose = true;
Why this change? Is it a left-over debug?

2021-02-15 12:30 UTC, stephanemagnenat commented on libgag/src/GraphicContext.cpp
> +				modes[i+j] = &mode;
That looks incorrect to me, it should rather be something like:
`int base_i = 0` in 1942,
then
`base_i += nummodes` in 1949
and
`modes[base_i + j]` here.

2021-02-15 12:30 UTC, stephanemagnenat commented on libgag/src/GraphicContext.cpp
> +		if (modes && (modes != (SDL_DisplayMode **)-1))
We are leaking modes in this function, but we were already before... to be fixed after this PR is merged.

2021-02-15 22:49 UTC, Quipyowert2 commented on libgag/include/KeyPress.h
> +	KeyPress(SDL_Keysym& key, bool pressed);
I changed it back to pass-by-value.

2021-02-15 22:50 UTC, Quipyowert2 commented on libgag/include/SDLGraphicContext.h
> +		static const bool verbose = true;
Yes, it was leftover from debugging.

2021-02-15 23:13 UTC, Quipyowert2 commented on libgag/src/GraphicContext.cpp
> +				modes[i+j] = &mode;
Yeah it's definitely incorrect the way I wrote it because it puts the address of a stack variable into a member variable. When getVideoModeListing returns the pointer is invalid. Also all the modes are being set to the same pointer.

2021-02-16 02:35 UTC, Quipyowert2 commented on libgag/src/GraphicContext.cpp
> +		if (modes && (modes != (SDL_DisplayMode **)-1))
Fixed by using a different pointer for iterating.

2021-02-16 07:53 UTC, stephanemagnenat commented
Thanks a lot for the quick reaction! The PR does not compile in the CI, I think because the file `debian/control` still has the old SDL dependencies and is used to install the necessary packages.

2021-02-16 08:01 UTC, stephanemagnenat commented on libgag/src/GraphicContext.cpp
> +		if (modes && (modes != (SDL_DisplayMode **)-1))
Ok! In the future, we could probably simplify this whole mode getting code by using a `std::deque<SDL_DisplayMode>`, emplacing them on the back and eating them on the front. That would solve the leak (#31). But for now your changes look good!

2021-02-16 12:40 UTC, stephanemagnenat commented on libgag/src/GraphicContext.cpp
> +#include <../../src/GlobalContainer.h>
This include breaks modularity, because `libgag` is not designed to depend on Globulation. I see that you use that for some wheel property. One proper way to do it is to put a `static bool` in `Screen` for example.

2021-02-16 12:41 UTC, stephanemagnenat commented on libgag/src/GraphicContext.cpp
> +			_gc = globalContainer->gfx;
Why do we need this? As described above, `libgag` should not depend on the `globalContainer`, which is Glob2-specific.

2021-02-17 00:02 UTC, Quipyowert2 commented on libgag/src/GraphicContext.cpp
> +#include <../../src/GlobalContainer.h>
I removed this include and it compiled fine but when I add a `static bool scrollWheelEnabled` and change the scroll wheel code to use it I get an ```undefined reference to `GAGGUI::Screen::scrollWheelEnabled'``` error.

2021-02-17 00:44 UTC, Quipyowert2 commented on libgag/src/GraphicContext.cpp
> +			_gc = globalContainer->gfx;
I think that part was to stop the game crashing if `_gc` was NULL.

2021-02-17 01:04 UTC, Quipyowert2 commented
With this pull request, the game works with and without OpenGL mode checked in my virtual machine (openSUSE 15.1) but the non-OpenGL mode in WSL1 (openSUSE 15.2 with VcXsrv) just prints a bunch of `Xlib:  extension "MIT-SHM" missing on display ":0".` and shows a blank screen. OpenGL in WSL1 works fine.

2021-02-17 03:54 UTC, Quipyowert2 commented
I changed the dependencies in `debian/control` to the SDL2 dependencies and Travis is still fetching the 1.2 dependencies.

2021-02-17 09:13 UTC, stephanemagnenat commented
I do not know why Travis is still fetching the old dependencies, as I see no other place where the SDL package to be installed is listed. @krichter722 any idea?

Once this is solved, I'll merge that in. @Quipyowert2 is it ok for you if I squash these changes into a single commit?

2021-02-17 09:44 UTC, stephanemagnenat commented
My trial in #39 did not work because the packages are installed _outside_ the Docker. @krichter722 do you know how to install dependencies in the docker and not outside?

2021-02-17 10:59 UTC, stephanemagnenat commented
I think I got it, through the `DEPS` variable.

2021-02-17 11:13 UTC, stephanemagnenat commented
Ok, so the compilation in CI is now fixed in #39, but the port does not work for me (see #40), so we need fixing before merging otherwise we'll break master.

2021-02-17 14:20 UTC, stephanemagnenat commented
This has been merged as port of #39.

2021-02-17 14:20 UTC, closed without merging