More iterator fixes
Globulation2/glob2 pull request #79
Opened 2023-04-17 01:19 UTC by Quipyowert2

Here's some more fixes for iterators. See issue #74 and PR #75 for an explanation. I think the assertion failure only happens in debug builds when building with Visual Studio's `cl.exe`, but it *might* be undefined behavior to attempt to increment an iterator that is pointing at the end, so it could cause problems in release builds too. I don't know for sure because I haven't read the C++ draft or bought a copy of C++ standard document. [Is it allowed to increment an end iterator?](https://stackoverflow.com/a/39820063/8890345) says it's undefined.

2023-04-17 08:39 UTC, stephanemagnenat requested changes
I reviewed on my phone, so I might have missed some things, but besides what I think is a bug (see my comment), other changes look good to me.

2023-04-18 16:20 UTC, Quipyowert2 commented on src/YOGServer.cpp
>  			playerList.erase(i);
I don't think it matters whether `i` is assigned to the result of erase because the very next line is a break, so there's no possible way the iterator could be incremented past the end. So it was correct the way it was before I patched it.

Should I remove this commit from the PR?

2023-04-18 18:02 UTC, stephanemagnenat commented on src/YOGServer.cpp
>  			playerList.erase(i);
Ah, you are right. Sorry I missed that, I was looking at the changes on the phone. Yes maybe let's remove this commit from the PR, then it is ready to be merged! :-)

2023-04-18 23:22 UTC, Quipyowert2 commented
YOGServer.cpp changes have been undone, so now it should be ready to merge.

2023-04-19 13:30 UTC, merged

2023-04-19 13:30 UTC, stephanemagnenat commented
Great! Done, thanks!